from enum import IntEnum


class INS(IntEnum):
    APPLICATION_BLOCK = 0x1E
    APPLICATION_UNBLOCK = 0x18
    CARD_BLOCK = 0x16
    EXTERNAL_AUTHENTICATE = 0x82
    GENERATE_AC = 0xAE
    GET_CHALLENGE = 0x84
    GET_DATA = 0xCA
    GET_PROCESSING_OPTIONS = 0xA8
    INTERNAL_AUTHENTICATE = 0x88
    PIN_CHANGE_UNBLOCK = 0x24
    READ_RECORD = 0xB2
    SELECT = 0xA4
    VERIFY = 0x20
